# This workflow will triage pull requests and apply a label based on the paths 
# that are modified and matched in the.github/labeler.yml configuration
#
# BOF
---

name: Pull Request Labeler
run-name: "Pull Request (PR) #${{ github.event.number }} Labeler"
on: 
  pull_request:
    types: 
    - opened
    - synchronize
    - reopened
    - ready_for_review
    - labeled
    - unlabeled
## ---------------------------------------------------
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    ## ---------------------------------------------------
    # src: https://github.com/actions/labeler
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

...
# EOF